### ISSUE TITLE
blitz-replays analyze

### ISSUE THREAD

**Issue by Jylpah** [Jylpah/blitz-replays#25]
_Design document_

`blitz-replays analyze` is a command to analyze replays and print various stats. 

# Requirements

### 1. Can read replays from files (JSON) or database (SQLite)

Consider using `blitzstats.BackEnd()` since it would add support for MongoDB

### 2. Filter replays

Filter replays to analyze based on: 
- player / `account_id`
- tank
- tier (well, tank)
- battle played
- in platoon / solo
- battle result (win/loss/draw)
- game mode (Regular, special modes)
- battle mode (Encounter/Supremacy)
- map

### 3. Player stats

Fetch player stats from WG API `tanks/stats/`. Three options for "player stats" to show in analysis: 
1. Average WR
2. WR in a tank played
3. WR at tier

Options 2-3 are problematic in edge cases where there are only very few battles. Should there be a lower limit for battles before the WR "becomes valid"? 

### 4. Configurable analysis like in the old version

Have look at the `BattleCategorization()` and consider refactoring to something more solid.

**Comment by Jylpah** [comment]
First working version released 🎉 

```
pip install git+https://github.com/Jylpah/blitz-replays.git
```

**Comment by Jylpah** [comment]
### Status with 0.5.11

- [x] Replay analysis works and is fast.
- [x] Support for user configurable reports and field through a TOML config file 
- [x] Export reports to a tab-separated file that can be opened with Excel

### Todo

- [ ] Database cache for API stats
- [ ] `--filter` to filter replays based on a criteria
